easy_admin:
    site_name: '<strong>VinnyVixi.com DASHBOARD</strong>'
    formats:
        date: 'j/m/Y'
    design:
        assets:
            css:
                # ...
                - 'css/admin.css'
        menu:
            - { label: 'Retour au site', url: 'https://vinnyvixi.com/', rel: 'index', icon: home }
            - label: 'Beats'
              children: [{ entity: 'Beat', rel: 'dns-prefetch preconnect', permission : 'ROLE_USER', icon: music, label: 'Mes beats'}
                         { entity: 'Filtre',rel: 'dns-prefetch preconnect', permission : 'ROLE_USER', icon: filter }]
              permission: 'ROLE_USER'
            - label: 'Videos'
              children:
                  - { entity: 'Video', rel: 'dns-prefetch preconnect', permission : 'ROLE_USER', icon: video,label: 'Mes videos'}
                  - { entity: 'SectionVideo', rel: 'dns-prefetch preconnect', permission : 'ROLE_USER', icon: columns}
              permission: 'ROLE_USER'
            - { entity: 'Licence',label : 'Licenses', rel: 'dns-prefetch preconnect', permission : 'ROLE_USER' , icon: money-check-alt}
            - { entity: 'Diapo',label : 'A propos', rel: 'dns-prefetch preconnect', permission : 'ROLE_USER' , icon: images}
#            - { entity: 'Message',label : 'Messages', rel: 'dns-prefetch preconnect', permission : 'ROLE_USER' , icon: envelope-open-text}
            - { entity: 'Admin',label : 'Comptes Administrateurs', rel: 'dns-prefetch preconnect', permission : 'ROLE_ADMIN' , icon: users-cog}
    list:
        title: "Liste des %%entity_label%%"
        batch_actions: ['delete']
        actions:
            - {name: 'show', icon: 'search', label: false, css_class: 'btn btn-secondary'}
            - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            - {name: 'search'}
    show:
        title: "Informations du %%entity_name%%"
    entities:

        Beat :
            label: 'Beats'
            class : App\Entity\Beat
            new :
                title : 'Ajouter un Beat'
                fields :
                    - {property: 'beatImage' , type : 'vich_image', label : "Illustration (taille optimisé : 132x132)", help : "Format .jpeg/jpg/png/svg"}
                    - {property: 'beatFile' , type : 'file', label : "Fichier audio",type_options: { required: false }}
#                    - {property: 'iframe' , type : 'text', label : "Source iframe (Remplace le fichier audio)", help : "Entrez ici la source (src) d'une balise iframe <br>Exemple : <strong>//www.beatstars.com/embed/track/?id=4141341</strong>" }
                    - {property: 'titre' , type : 'text'}
                    - {property: 'artiste' , type : 'text', label : 'Prod. by', help: "Si vide : Vinny Vixi"}
                    - {property: 'bpm' , type : 'text'}
                    - {property: 'genre' , type : 'entity', type_options: { class: 'App\Entity\Filtre' } }


            edit:
                title: 'Modifier un Beat'
                fields:
                    - {property: 'beatImage' , type: 'vich_image', label: "Illustration (taille optimisé : 132x132)", help : "Format .jpeg/jpg/png/svg"}
                    - {property: 'beatName' ,label : "Nom du fichier", type : 'text',type_options: { required: false, disabled: true } }
                    - {property: 'beatFile' , type: 'file', label: "Fichier audio", type_options: { required: false } }
#                    - {property: 'iframe' , type : 'text', label : "Source iframe (Remplace le fichier audio)", help : "Entrez ici la source (src) d'une balise iframe <br>Exemple : <strong>//www.beatstars.com/embed/track/?id=4141341</strong>" }
                    - {property: 'titre' , type: 'text', help: "Titre affiché sur le site"}
                    - {property: 'artiste' , type: 'text', label : 'Prod. by', help: "Si vide : Vinny Vixi"}
                    - {property: 'bpm' , type: 'text'}
                    - {property: 'genre' , type : 'entity', type_options: { class: 'App\Entity\Filtre' } }

            list:
                fields:
                    - {property: 'beatImage' , type : 'image', template: 'includes/vich_uploader_image.html.twig', label : "Illustration", css_class: 'is-hidden-touch'}
                    - {property: 'titre' , type: 'text'}
                    - {property: 'beatFile', label : "", type : 'audio', template: 'includes/vich_uploader_audio.html.twig'}
                    - {property: 'bpm' , type: 'text', css_class: 'is-hidden-mobile'}
                    - {property: 'genre' , type: 'text', css_class: 'is-hidden-mobile'}
#                    - {property: 'iframe', label: 'Lien Beatstar', type: 'boolean'}
            show:
                fields:
                    - {property: 'titre' , type: 'text', help: "Titre affiché sur le site"}
                    - {property: 'beatImage' , type : 'image', template: 'includes/vich_uploader_image.html.twig', label : "Illustration"}
                    - {property: 'beatName' ,label : "Nom du fichier", type : 'text',type_options: { required: false }}
                    - {property: 'beatFile', label : "Player", type : 'audio', template: 'includes/vich_uploader_audio.html.twig'}
#                    - {property: 'iframe' , type : 'text', label : "Iframe"}
                    - {property: 'artiste' , type: 'text', label : 'Prod. by', help: "Si vide : Vinny Vixi"}
                    - {property: 'bpm' , type: 'text'}
                    - {property: 'genre' , type: 'text'}


        Licence:
            label: 'Licences'
            class: App\Entity\Licence
            list:
                fields:
                    - {property: 'titre_fr' , type: 'text', label: 'Titre'}
#                    - {property: 'titre' , type: 'text'}
                    - {property: 'euro', type: 'text'}
#                    - {property: 'dollar', type: 'text'}
                    - {property: 'info_1_fr' , type: 'text', css_class: 'is-hidden-touch', label: 'info 1'}
                    - {property: 'info_2_fr' , type: 'text', css_class: 'is-hidden-touch', label: 'info 2'}
                    - {property: 'info_3_fr' , type: 'text', css_class: 'is-hidden-touch', label: 'info 3'}
                    - {property: 'info_4_fr' , type: 'text', css_class: 'is-hidden-touch', label: 'info 4'}
                    - {property: 'info_5_fr' , type: 'text', css_class: 'is-hidden-touch', label: 'info 5'}
                    - {property: 'info_6_fr' , type: 'text', css_class: 'is-hidden-touch', label: 'info 6'}
#                    - {property: 'color' , type: 'text'}
            form:
                fields:
                    - { type: 'tab',columns: 4, label: 'En Anglais' }
                    - {property: 'titre' , type: 'text'}
                    - {property: 'dollar', type: 'text'}
                    - {property: 'info_1' , type: 'text'}
                    - {property: 'info_2' , type: 'text'}
                    - {property: 'info_3' , type: 'text'}
                    - {property: 'info_4' , type: 'text'}
                    - {property: 'info_5' , type: 'text'}
                    - {property: 'info_6' , type: 'text'}
                    - { type: 'tab',columns: 4, label: 'En Français' }
                    - {property: 'titre_fr' , type: 'text'}
                    - {property: 'euro', type: 'text'}
                    - {property: 'info_1_fr' , type: 'text'}
                    - {property: 'info_2_fr' , type: 'text'}
                    - {property: 'info_3_fr' , type: 'text'}
                    - {property: 'info_4_fr' , type: 'text'}
                    - {property: 'info_5_fr' , type: 'text'}
                    - {property: 'info_6_fr' , type: 'text'}
                    - { type: 'tab',columns: 4, label: 'Couleur' }
                    - {property: 'color' , type: 'choice',type_options: {choices: {'Bleu':'info','Vert':'success','Rouge':'danger', 'Jaune' : 'warning'}}}
            show:
                title: "Informations de la %%entity_name%%"



        SectionVideo:
            label: 'Sections'
            class: App\Entity\SectionVideo
            form:
                title: 'Ajouter une rubrique de videos'
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'couleur' , type: 'choice', help: 'gris foncé par défaut', type_options: {choices: {'Bleu':'info','Vert':'success','Rouge':'danger', 'Jaune' : 'warning'}}}
            edit:
                title: 'Modifier une rubrique de videos'
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'couleur' , type: 'choice',type_options: {choices: {'Bleu':'info','Vert':'success','Rouge':'danger', 'Jaune': 'warning'}}}

            list:
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'couleur' , type: 'text', label: "Couleur"}
            show:
                title: "Informations de la %%entity_name%%"
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'couleur' , type: 'text', label: "Couleur"}

        Video:
            label: 'Videos'
            class: App\Entity\Video
            form:
                title: 'Ajouter une video'
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'info' , type: 'text', label: "Info"}
                    - {property: 'link' , type: 'text', label: "lien url", help: "Entrez ici l'ID de la video youtube<br>Exemple : dans l'url https://www.youtube.com/embed/<strong>HhQTPqq4XFY</strong><br>L'ID est <strong>HhQTPqq4XFY</strong>"}
                    - {property: 'section' ,type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\SectionVideo' } }
            edit:
                title: 'Modifier une video'
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'info' , type: 'text', label: "Info"}
                    - {property: 'link' , type: 'text', label: "lien url", help: "Entrez ici l'ID de la video youtube<br>Exemple : dans l'url https://www.youtube.com/embed/<strong>HhQTPqq4XFY</strong><br>L'ID est <strong>HhQTPqq4XFY</strong>"}
                    - {property: 'section' ,type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\SectionVideo' } }

            list:
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'info' , type: 'text', label: "Info", css_class: 'is-hidden-touch'}
                    - {property: 'link' , type: 'text', label: "lien url", css_class: 'is-hidden-touch'}
                    - {property: 'section' , type: 'text'}
            show:
                title: "Informations de la %%entity_name%%"

        Filtre:
            label: 'Filtres'
            class: App\Entity\Filtre
            form:
                title: 'Ajouter un filtre'
                fields:
                    - {property: 'genre',type: 'text', label: "Genre" }
            edit:
                title: 'Modifier un filtre'
                fields:
                    - {property: 'genre',type: 'text', label: "Genre" }
            list:
                fields:
                    - {property: 'genre',type: 'text', label: "Genre"}
            show:
                fields:
                    - {property: 'genre' , type: 'text', label: "Genre"}

        Diapo:
            label: 'Images'
            class: App\Entity\Diapo
            form:
                fields:
                    - { type: 'tab', label: 'En Anglais' }
                    - {property: 'titre' , type: 'text', label: "Titre", help: "Entrez ici le titre de la diapo en Anglais"}
                    - {property: 'text' , type: 'text_editor', label: "Text", help: "Entrez ici le texte de la diapo en Anglais"}
                    - { type: 'tab', label: 'En Français' }
                    - {property: 'titre_fr' , type: 'text', label: "Titre", help: "Entrez ici le titre de la diapo en Français"}
                    - {property: 'text_fr' , type: 'text_editor', label: "Text", help: "Entrez ici le texte de la diapo en Français"}
                    - { type: 'tab', label: 'Upload du fichier image' }
                    - {property: 'diapoImage' , type: 'vich_image', label: "Image de fond",type_options: { required: false }, help: "Format optimisé : 800 x 480 pixels .jpeg/jpg/png/svg" }
            list:
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'text' , type: 'text', label: "Text", css_class: 'is-hidden-touch'}
                    - {property: 'beatImage' , type : 'image', template: 'includes/vich_uploader_diapo_image.html.twig', label : "Illustration", css_class: 'is-hidden-touch'}
            show:
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'text' , type: 'text', label: "Text"}
                    - {property: 'titre_fr' , type: 'text', label: "Titre"}
                    - {property: 'text_fr' , type: 'text', label: "Text"}
                    - {property: 'beatImage' , type : 'image', template: 'includes/vich_uploader_diapo_image.html.twig', label : "Illustration"}

        Admin:
            label: 'Comptes Administrateur'
            class: App\Entity\Admin
            password_encoding: { algorithm: 'bcrypt', cost: 12 }
#            new:
#                title: 'Ajouter un compte Administrateur'
#                fields:
#                    - {property: 'email' , type: 'text', label: "email"}
#                    - {property: 'password' , type: 'repeated', label: "Mot de passe"}
#                    - {property: 'roles' ,label : "Roles", type: 'collection'}
            edit:
                title: 'Modifier un compte Administrateur'
                fields:
                    - {property: 'email' , type: 'text', label: "Email"}
#                    - {property: 'password' , type: 'repeated', label: "Mot de passe"}
                    - {property: 'roles' ,label : "Roles", type: 'collection'}
            list:
                actions: ['-new']
                fields:
                    - {property: 'email' , type: 'email', label: "Email"}
                    - {property: 'roles' , type: 'array', label: "Roles"}
                    - {property: 'date' , type: 'date', format: 'j/n/Y'}
            show:
                title: "Informations de l'%%entity_name%%"
                fields:
                    - {property: 'email' , type: 'email', label: "Email"}
                    - {property: 'roles' , type: 'array', label: "Roles"}
                    - {property: 'date', type: 'date', format: 'j/n/Y', label: 'Date de création'}


#        Message:
#            label: 'Messages'
#            class: App\Entity\Message
#            disabled_actions: ['new', 'edit']
#
#            list:
#                fields:
#                    - {property: 'nom' , type: 'text'}
#                    - {property: 'prenom', type: 'text'}
#                    - {property: 'email', type: 'text'}
#                    - {property: 'objet' , type: 'text'}
#                    - {property: 'message' , type: 'text'}
#                    - {property: 'date' , type: 'datetime', format: 'j/n/Y H:i:s'}
#            show:
#                fields:
#                    - {property: 'nom' , type: 'text'}
#                    - {property: 'prenom', type: 'text'}
#                    - {property: 'email', type: 'text'}
#                    - {property: 'objet' , type: 'text'}
#                    - {property: 'message' , type: 'text'}
#                    - {property: 'date' , type: 'datetime', format: 'j/n/Y H:i:s'}