easy_admin:
    site_name: '<strong>VinnyVixi.com DASHBOARD</strong>'
    formats:
        date: 'j/m/Y'
    design:
        assets:
            # all kinds of assets are supported and linked accordingly
            css:
                - '//example.org/css/admin1.css'
                - 'http://example.org/css/admin2.css'
                - 'https://example.org/css/admin3.css'
                - '/bundles/user/css/admin4.css'
                - 'bundles/app/css/admin5.css'
            js:
                - '//example.org/js/admin1.js'
                - 'http://example.org/js/admin2.js'
                - 'https://example.org/js/admin3.js'
                - '/bundles/user/js/admin4.js'
                - 'bundles/app/js/admin5.js'
        menu:
            - { label: 'Retour au site', url: 'https://vinnyvixi.com/adm', rel: 'index', icon: home }
            - { entity: 'Beat',label : 'Beats', rel: 'dns-prefetch preconnect', permission : 'ROLE_USER' }
            - { entity: 'Message',label : 'Messages', rel: 'dns-prefetch preconnect', permission : 'ROLE_USER' }
            - { entity: 'Licence',label : 'Licences', rel: 'dns-prefetch preconnect', permission : 'ROLE_USER' }
            - label: 'Videos'
              children: ['SectionVideo','Video']
              permission: 'ROLE_USER'
            - { entity: 'Filtre',label : 'Filtres', rel: 'dns-prefetch preconnect', permission : 'ROLE_USER' }
            - { entity: 'Admin',label : 'Comptes Administrateurs', rel: 'dns-prefetch preconnect', permission : 'ROLE_ADMIN' }
    list:
        actions: ['edit', 'search']
    entities:
        Beat :
            class : App\Entity\Beat
            form :
                title : 'Ajouter un Beat'
                fields :
                    - {property: 'beatImage' , type : 'vich_image', label : "Illustration (taille optimisé : 132x132)", help : "Format .jpeg/jpg/png"}
                    - {property: 'beatFile' , type : 'file', label : "Fichier audio",type_options: { required: false }}
                    - {property: 'iframe' , type : 'text', label : "Source iframe (Remplace le fichier audio)", help : "Entrez ici la source (src) d'une balise iframe <br>Exemple : <strong>//www.beatstars.com/embed/track/?id=4141341</strong>" }
                    - {property: 'titre' , type : 'text'}
                    - {property: 'artiste' , type : 'text', label : 'Prod. by'}
                    - {property: 'bpm' , type : 'text'}
                    - {property: 'genre' , type : 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Filtre' } }
#                    - {property: 'genre' , type : 'choice',type_options: {choices: {'RAP FR':'RAP FR','RAP US':'RAP US','DRILL':'DRILL','GRIME':'GRIME','TRAP':'TRAP','TRAP SOUL':'TRAP SOUL'}}}


            edit:
                title: 'Modifier un Beat'
                fields:
                    - {property: 'beatImage' , type: 'vich_image', label: "Illustration (taille optimisé : 132x132)"}
                    - {property: 'beatFile' , type: 'file', label: "Fichier audio", type_options: { required: false }}
                    - {property: 'iframe' , type : 'text', label : "Source iframe (Remplace le fichier audio)", help : "Entrez ici la source (src) d'une balise iframe <br>Exemple : <strong>//www.beatstars.com/embed/track/?id=4141341</strong>" }
                    - {property: 'titre' , type: 'text'}
                    - {property: 'artiste' , type: 'text', label : 'Prod. by'}
                    - {property: 'bpm' , type: 'text'}
                    - {property: 'genre' , type : 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Filtre' } }
#                    - {property: 'genre' , type: 'choice',type_options: {choices: {'RAP FR':'RAP FR','RAP US':'RAP US','DRILL':'DRILL','GRIME':'GRIME','TRAP':'TRAP','TRAP SOUL':'TRAP SOUL'}}}

            list:
                batch_actions: ['delete']
                fields:
                    - {property: 'beatImage' , type : 'image', template: 'includes/vich_uploader_image.html.twig', label : "Illustration"}
                    - {property: 'beatName', type: 'text', label : "Nom du fichier audio"}
                    - {property: 'beatFile', label : "", type : 'audio', template: 'includes/vich_uploader_audio.html.twig'}
                    - {property: 'iframe' , type : 'text', label : "Lien iframe" }
                    - {property: 'titre' , type: 'text'}
                    - {property: 'artiste' , type: 'text', label : 'Prod. by'}
                    - {property: 'bpm' , type: 'text'}
                    - {property: 'genre' , type: 'text'}

        Message:
            class: App\Entity\Message
            disabled_actions: ['new', 'edit']

            list:
                actions: ['show']
                batch_actions: ['delete']
                fields:
                    - {property: 'nom' , type: 'text'}
                    - {property: 'prenom', type: 'text'}
                    - {property: 'email', type: 'text'}
                    - {property: 'objet' , type: 'text'}
                    - {property: 'message' , type: 'text'}
                    - {property: 'date' , type: 'date', format: 'j/n/Y'}
        Licence:
            class: App\Entity\Licence
            list:
                batch_actions: ['delete']
                fields:
                    - {property: 'titre' , type: 'text'}
                    - {property: 'euro', type: 'text'}
                    - {property: 'dollar', type: 'text'}
                    - {property: 'info_1' , type: 'text'}
                    - {property: 'info_2' , type: 'text'}
                    - {property: 'info_3' , type: 'text'}
                    - {property: 'info_4' , type: 'text'}
                    - {property: 'info_5' , type: 'text'}
                    - {property: 'info_6' , type: 'text'}
                    - {property: 'color' , type: 'text'}
            form:
                batch_actions: ['delete']
                fields:
                    - {property: 'titre' , type: 'text'}
                    - {property: 'euro', type: 'text'}
                    - {property: 'dollar', type: 'text'}
                    - {property: 'info_1' , type: 'text'}
                    - {property: 'info_2' , type: 'text'}
                    - {property: 'info_3' , type: 'text'}
                    - {property: 'info_4' , type: 'text'}
                    - {property: 'info_5' , type: 'text'}
                    - {property: 'info_6' , type: 'text'}
                    - {property: 'color' , type: 'choice',type_options: {choices: {'Bleu':'link','Vert':'success','Rouge':'danger', 'Jaune' : 'warning'}}}

            edit:
                batch_actions: ['delete']
                fields:
                    - {property: 'titre' , type: 'text'}
                    - {property: 'euro', type: 'text'}
                    - {property: 'dollar', type: 'text'}
                    - {property: 'info_1' , type: 'text'}
                    - {property: 'info_2' , type: 'text'}
                    - {property: 'info_3' , type: 'text'}
                    - {property: 'info_4' , type: 'text'}
                    - {property: 'info_5' , type: 'text'}
                    - {property: 'info_6' , type: 'text'}
                    - {property: 'color' , type: 'choice',type_options: {choices: {'Bleu':'link','Vert':'success','Rouge':'danger', 'Jaune' : 'warning'}}}

        Admin :
            class : App\Entity\Admin
            form :
                title : 'Ajouter un compte Administrateur'
                fields :
                    - {property: 'email' , type : 'text', label : "email"}
                    - {property: 'password' , type : 'password', label : "Mot de passe"}
#                    - {property: 'roles' ,label : "Roles", type: 'choice',type_options: {choices: {'ADMIN':['ROLE_USER'],'SUPER-ADMIN':['ROLE_ADMIN']} }}
            edit:
                title: 'Modifier un compte Administrateur'
                fields:
                    - {property: 'email' , type: 'text', label: "email"}
                    - {property: 'password' , type: 'text', label: "Mot de passe"}
#                    - {property: 'roles' ,label : "Roles", type: 'choice',type_options: {choices: {'ADMIN':['ROLE_USER'],'SUPER-ADMIN':['ROLE_ADMIN']} }}


            list:
                batch_actions: ['delete']
                fields:
                    - {property: 'email' , type: 'text', label: "email"}
                    - {property: 'roles' , type: 'array', label: "Roles"}
                    - {property: 'date' , type: 'date', format: 'j/n/Y'}


        SectionVideo:
            label: 'Sections'
            class: App\Entity\SectionVideo
            form:
                title: 'Ajouter une rubrique de videos'
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'couleur' , type: 'choice',type_options: {choices: {'Bleu':'info','Vert':'success','Rouge':'danger', 'Jaune' : 'warning'}}}
            edit:
                title: 'Modifier une rubrique de videos'
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'couleur' , type: 'choice',type_options: {choices: {'Bleu':'info','Vert':'success','Rouge':'danger', 'Jaune': 'warning'}}}

            list:
                batch_actions: ['delete']
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'couleur' , type: 'text', label: "Couleur"}

        Video:
            label: 'Videos'
            class: App\Entity\Video
            form:
                title: 'Ajouter une video'
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'link' , type: 'text', label: "lien url", help: "Entrez ici l'ID de la video youtube<br>Exemple : dans l'url https://www.youtube.com/embed/<strong>HhQTPqq4XFY</strong><br>L'ID est <strong>HhQTPqq4XFY</strong>"}
                    - {property: 'section' ,type: 'easyadmin_autocomplete'}
            edit:
                title: 'Modifier une video'
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'link' , type: 'text', label: "lien url", help: "Entrez ici l'ID de la video youtube<br>Exemple : dans l'url https://www.youtube.com/embed/<strong>HhQTPqq4XFY</strong><br>L'ID est <strong>HhQTPqq4XFY</strong>"}
                    - {property: 'section' ,type: 'easyadmin_autocomplete'}

            list:
                batch_actions: ['delete']
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'link' , type: 'text', label: "lien url"}
                    - {property: 'section' , type: 'text'}

        Filtre:
            label: 'Filtres'
            class: App\Entity\Filtre
            form:
                title: 'Ajouter un filtre'
                fields:
                    - {property: 'genre' }
            edit:
                title: 'Modifier un filtre'
                fields:
                    - {property: 'genre' }
            list:
                batch_actions: ['delete']
                fields:
                    - {property: 'genre'}