easy_admin:
    site_name: '<strong>VinnyVixi.com DASHBOARD</strong>'
    formats:
        date: 'j/m/Y'
    design:
        assets:
            css:
                # ...
                - 'css/admin.css'

        menu:
            - { label: 'Retour au site', url: 'https://vinnyvixi.com/', rel: 'index', icon: home }
            - label: 'Beats'
              children: [{ entity: 'Beat', rel: 'dns-prefetch preconnect', permission : 'ROLE_USER'}
                         { entity: 'Filtre',rel: 'dns-prefetch preconnect', permission : 'ROLE_USER' }]
              permission: 'ROLE_USER'
            - label: 'Videos'
              children: ['SectionVideo','Video']
              permission: 'ROLE_USER'
            - { entity: 'Licence',label : 'Licenses', rel: 'dns-prefetch preconnect', permission : 'ROLE_USER' }
            - { entity: 'Diapo',label : 'Carrousel', rel: 'dns-prefetch preconnect', permission : 'ROLE_USER' }
            - { entity: 'Message',label : 'Messages', rel: 'dns-prefetch preconnect', permission : 'ROLE_USER' }
            - { entity: 'Admin',label : 'Comptes Administrateurs', rel: 'dns-prefetch preconnect', permission : 'ROLE_ADMIN' }
    list:
        actions: ['edit', 'search']
    entities:
        Beat :
            label: 'Beats'
            class : App\Entity\Beat
            form :
                title : 'Ajouter un Beat'
                fields :
                    - {property: 'beatImage' , type : 'vich_image', label : "Illustration (taille optimisé : 132x132)", help : "Format .jpeg/jpg/png"}
                    - {property: 'beatFile' , type : 'file', label : "Fichier audio",type_options: { required: false }}
                    - {property: 'iframe' , type : 'text', label : "Source iframe (Remplace le fichier audio)", help : "Entrez ici la source (src) d'une balise iframe <br>Exemple : <strong>//www.beatstars.com/embed/track/?id=4141341</strong>" }
                    - {property: 'titre' , type : 'text'}
                    - {property: 'artiste' , type : 'text', label : 'Prod. by'}
                    - {property: 'bpm' , type : 'text'}
                    - {property: 'genre' , type : 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Filtre' } }


            edit:
                title: 'Modifier un Beat'
                fields:
                    - {property: 'beatImage' , type: 'vich_image', label: "Illustration (taille optimisé : 132x132)"}
                    - {property: 'beatFile' , type: 'file', label: "Fichier audio", type_options: { required: false }}
                    - {property: 'iframe' , type : 'text', label : "Source iframe (Remplace le fichier audio)", help : "Entrez ici la source (src) d'une balise iframe <br>Exemple : <strong>//www.beatstars.com/embed/track/?id=4141341</strong>" }
                    - {property: 'titre' , type: 'text'}
                    - {property: 'artiste' , type: 'text', label : 'Prod. by'}
                    - {property: 'bpm' , type: 'text'}
                    - {property: 'genre' , type : 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Filtre' } }

            list:
                batch_actions: ['delete']
                fields:
                    - {property: 'beatImage' , type : 'image', template: 'includes/vich_uploader_image.html.twig', label : "Illustration"}
                    - {property: 'beatName', type: 'text', label : "Nom du fichier audio"}
                    - {property: 'beatFile', label : "", type : 'audio', template: 'includes/vich_uploader_audio.html.twig'}
                    - {property: 'iframe' , type : 'text', label : "Lien iframe" }
                    - {property: 'titre' , type: 'text'}
                    - {property: 'artiste' , type: 'text', label : 'Prod. by'}
                    - {property: 'bpm' , type: 'text'}
                    - {property: 'genre' , type: 'text'}

        Message:
            label: 'Messages'
            class: App\Entity\Message
            disabled_actions: ['new', 'edit']

            list:
                actions: ['show']
                batch_actions: ['delete']
                fields:
                    - {property: 'nom' , type: 'text'}
                    - {property: 'prenom', type: 'text'}
                    - {property: 'email', type: 'text'}
                    - {property: 'objet' , type: 'text'}
                    - {property: 'message' , type: 'text'}
                    - {property: 'date' , type: 'datetime', format: 'j/n/Y H:i:s'}
            show:
                fields:
                    - {property: 'nom' , type: 'text'}
                    - {property: 'prenom', type: 'text'}
                    - {property: 'email', type: 'text'}
                    - {property: 'objet' , type: 'text'}
                    - {property: 'message' , type: 'text'}
                    - {property: 'date' , type: 'datetime', format: 'j/n/Y H:i:s'}
        Licence:
            label: 'Licences'
            class: App\Entity\Licence
            list:
                batch_actions: ['delete']
                fields:
                    - {property: 'titre' , type: 'text'}
                    - {property: 'euro', type: 'text'}
                    - {property: 'dollar', type: 'text'}
                    - {property: 'info_1' , type: 'text'}
                    - {property: 'info_2' , type: 'text'}
                    - {property: 'info_3' , type: 'text'}
                    - {property: 'info_4' , type: 'text'}
                    - {property: 'info_5' , type: 'text'}
                    - {property: 'info_6' , type: 'text'}
                    - {property: 'color' , type: 'text'}
            form:
                batch_actions: ['delete']
                fields:
                    - {property: 'titre' , type: 'text'}
                    - {property: 'euro', type: 'text'}
                    - {property: 'dollar', type: 'text'}
                    - {property: 'info_1' , type: 'text'}
                    - {property: 'info_2' , type: 'text'}
                    - {property: 'info_3' , type: 'text'}
                    - {property: 'info_4' , type: 'text'}
                    - {property: 'info_5' , type: 'text'}
                    - {property: 'info_6' , type: 'text'}
                    - {property: 'color' , type: 'choice',type_options: {choices: {'Bleu':'info','Vert':'success','Rouge':'danger', 'Jaune' : 'warning'}}}

            edit:
                batch_actions: ['delete']
                fields:
                    - {property: 'titre' , type: 'text'}
                    - {property: 'euro', type: 'text'}
                    - {property: 'dollar', type: 'text'}
                    - {property: 'info_1' , type: 'text'}
                    - {property: 'info_2' , type: 'text'}
                    - {property: 'info_3' , type: 'text'}
                    - {property: 'info_4' , type: 'text'}
                    - {property: 'info_5' , type: 'text'}
                    - {property: 'info_6' , type: 'text'}
                    - {property: 'color' , type: 'choice',type_options: {choices: {'Bleu':'info','Vert':'success','Rouge':'danger', 'Jaune' : 'warning'}}}

        Admin :
            label: 'Comptes Administrateur'
            class : App\Entity\Admin
            form :
                title : 'Ajouter un compte Administrateur'
                fields :
                    - {property: 'email' , type : 'text', label : "email"}
                    - {property: 'password' , type : 'password', label : "Mot de passe"}
#                    - {property: 'roles' ,label : "Roles", type: 'choice',type_options: {choices: {'ADMIN':['ROLE_USER'],'SUPER-ADMIN':['ROLE_ADMIN']} }}
            edit:
                title: 'Modifier un compte Administrateur'
                fields:
                    - {property: 'email' , type: 'text', label: "email"}
                    - {property: 'password' , type: 'text', label: "Mot de passe"}
#                    - {property: 'roles' ,label : "Roles", type: 'choice',type_options: {choices: {'ADMIN':['ROLE_USER'],'SUPER-ADMIN':['ROLE_ADMIN']} }}


            list:
                batch_actions: ['delete']
                fields:
                    - {property: 'email' , type: 'text', label: "email"}
                    - {property: 'roles' , type: 'array', label: "Roles"}
                    - {property: 'date' , type: 'date', format: 'j/n/Y'}


        SectionVideo:
            label: 'Sections'
            class: App\Entity\SectionVideo
            form:
                title: 'Ajouter une rubrique de videos'
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'couleur' , type: 'choice',type_options: {choices: {'Bleu':'info','Vert':'success','Rouge':'danger', 'Jaune' : 'warning'}}}
            edit:
                title: 'Modifier une rubrique de videos'
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'couleur' , type: 'choice',type_options: {choices: {'Bleu':'info','Vert':'success','Rouge':'danger', 'Jaune': 'warning'}}}

            list:
                batch_actions: ['delete']
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'couleur' , type: 'text', label: "Couleur"}

        Video:
            label: 'Videos'
            class: App\Entity\Video
            form:
                title: 'Ajouter une video'
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'info' , type: 'text', label: "Info"}
                    - {property: 'link' , type: 'text', label: "lien url", help: "Entrez ici l'ID de la video youtube<br>Exemple : dans l'url https://www.youtube.com/embed/<strong>HhQTPqq4XFY</strong><br>L'ID est <strong>HhQTPqq4XFY</strong>"}
                    - {property: 'section' ,type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\SectionVideo' } }
            edit:
                title: 'Modifier une video'
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'info' , type: 'text', label: "Info"}
                    - {property: 'link' , type: 'text', label: "lien url", help: "Entrez ici l'ID de la video youtube<br>Exemple : dans l'url https://www.youtube.com/embed/<strong>HhQTPqq4XFY</strong><br>L'ID est <strong>HhQTPqq4XFY</strong>"}
                    - {property: 'section' ,type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\SectionVideo' } }

            list:
                batch_actions: ['delete']
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre"}
                    - {property: 'info' , type: 'text', label: "Info"}
                    - {property: 'link' , type: 'text', label: "lien url"}
                    - {property: 'section' , type: 'text'}

        Filtre:
            label: 'Filtres'
            class: App\Entity\Filtre
            form:
                title: 'Ajouter un filtre'
                fields:
                    - {property: 'genre',type: 'text', label: "Genre" }
            edit:
                title: 'Modifier un filtre'
                fields:
                    - {property: 'genre',type: 'text', label: "Genre" }
            list:
                batch_actions: ['delete']
                fields:
                    - {property: 'genre',type: 'text', label: "Genre"}

        Diapo:
            label: 'Diapositives'
            class: App\Entity\Diapo
            form:
                title: 'Ajouter un Diapo'
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre", help: "Entrez ici le titre de la diapo"}
                    - {property: 'text' , type: 'textarea', label: "Text", help: "Entrez ici le texte de la diapo (250 caractères max)"}
                    - {property: 'diapoImage' , type: 'vich_image', label: "Image de fond",type_options: { required: false }, help: "Uploader une image de fond pour la diapo, Format optimisé : 2560 x 1440 pixels .jpeg/jpg/png" }



            edit:
                title: 'Modifier un Beat'
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre", help: "Entrez ici le titre de la diapo"}
                    - {property: 'text' , type: 'textarea', label: "Text", help: "Entrez ici le texte de la diapo (250 caractères max)" }
                    - {property: 'diapoImage' , type: 'vich_image', label: "Image de fond",type_options: { required: false }, help: "Uploader une image de fond pour la diapo, Format optimisé : 2560 x 1440 pixels .jpeg/jpg/png" }

            list:
                batch_actions: ['delete']
                fields:
                    - {property: 'titre' , type: 'text', label: "Titre", help: "Entrez ici le titre dde la diapo"}
                    - {property: 'text' , type: 'text', label: "Text", help: "Entrez ici le texte de la diapo (250 caractères max)" }
                    - {property: 'beatImage' , type : 'image', template: 'includes/vich_uploader_diapo_image.html.twig', label : "Illustration"}
