easy_admin:
    entities:
        Beat :
            class : App\Entity\Beat
            form :
                fields :
                    - {property: 'beatImage' , type : 'vich_image', label : "Illustration"}
                    - {property: 'beatName' , type : 'text', label : "Nom du fichier audio actuel"}
                    - {property: 'beatFile' , type : 'file', label : "Fichier audio"}
                    - {property: 'titre' , type : 'text'}
                    - {property: 'artiste' , type : 'text'}
                    - {property: 'album' , type : 'text'}
                    - {property: 'genre' , type : 'text'}
            list:
                fields:
                    - actions: ['edit', 'search']
                    - {property: 'beatImage' , type : 'image', template: 'includes/vich_uploader_image.html.twig', label : "Illustration"}
                    - {property: 'beatName', type: 'file'}
                    - { property: 'beatFile', type : 'audio', template: 'includes/vich_uploader_audio.html.twig' }
                    - {property: 'titre' , type: 'text'}
                    - {property: 'artiste' , type: 'text'}
                    - {property: 'album' , type: 'text'}
                    - {property: 'genre' , type: 'text'}
